flask_qa/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash

from .extensions import db 

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    password = db.Column(db.String(100))
    expert = db.Column(db.Boolean)
    admin = db.Column(db.Boolean)

    questions_asked = db.relationship(
        'Question', 
        foreign_keys='Question.asked_by_id', 
        backref='asker', 
        lazy=True
    )

    answers_requested = db.relationship(
        'Question',
        foreign_keys='Question.expert_id',
        backref='expert',
        lazy=True
    )

    @property
    def unhashed_password(self):
        raise AttributeError('Cannot view unhashed password!')

    @unhashed_password.setter
    def unhashed_password(self, unhashed_password):
        self.password = generate_password_hash(unhashed_password)

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.Text)
    answer = db.Column(db.Text)
    asked_by_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    expert_id = db.Column(db.Integer, db.ForeignKey('user.id'))

flask_qa/__init__.py
from flask import Flask 

from .commands import create_tables
from .extensions import db, login_manager
from .models import User
from .routes.auth import auth
from .routes.main import main

def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)

    login_manager.init_app(app)

    login_manager.login_view = 'auth.login'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    app.register_blueprint(main)
    app.register_blueprint(auth)

    app.cli.add_command(create_tables)

    return app

flask_qa/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash

from flask_qa.extensions import db
from flask_qa.models import User

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['name']
        unhashed_password = request.form['password']

        user = User(
            name=name, 
            unhashed_password=unhashed_password,
            admin=False,  
            expert=False
        )

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('auth.login'))

    return render_template('register.html')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form['name']
        password = request.form['password']

        user = User.query.filter_by(name=name).first()

        error_message = ''

        if not user or not check_password_hash(user.password, password):
            error_message = 'Could not login. Please check and try again.'

        if not error_message:
            login_user(user)
            return redirect(url_for('main.index'))

    return render_template('login.html')

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

flask_qa/routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required

from flask_qa.extensions import db
from flask_qa.models import Question, User

main = Blueprint('main', __name__)

@main.route('/')
def index():
    questions = Question.query.filter(Question.answer != None).all()

    context = {
        'questions' : questions
    }

    return render_template('home.html', **context)

@main.route('/ask', methods=['GET', 'POST'])
@login_required
def ask():
    if request.method == 'POST':
        question = request.form['question']
        expert = request.form['expert']

        question = Question(
            question=question, 
            expert_id=expert, 
            asked_by_id=current_user.id
        )

        db.session.add(question)
        db.session.commit()

        return redirect(url_for('main.index'))

    experts = User.query.filter_by(expert=True).all()

    context = {
        'experts' : experts
    }

    return render_template('ask.html', **context)

@main.route('/answer/<int:question_id>', methods=['GET', 'POST'])
@login_required
def answer(question_id):
    if not current_user.expert:
        return redirect(url_for('main.index'))

    question = Question.query.get_or_404(question_id)

    if request.method == 'POST':
        question.answer = request.form['answer']
        db.session.commit()

        return redirect(url_for('main.unanswered'))

    context = {
        'question' : question
    }

    return render_template('answer.html', **context)

@main.route('/question/<int:question_id>')
def question(question_id):
    question = Question.query.get_or_404(question_id)

    context = {
        'question' : question
    }

    return render_template('question.html', **context)

@main.route('/unanswered')
@login_required
def unanswered():
    if not current_user.expert:
        return redirect(url_for('main.index'))

    unanswered_questions = Question.query\
        .filter_by(expert_id=current_user.id)\
        .filter(Question.answer == None)\
        .all()

    context = {
        'unanswered_questions' : unanswered_questions
    }

    return render_template('unanswered.html', **context)

@main.route('/users')
@login_required
def users():
    if not current_user.admin:
        return redirect(url_for('main.index'))

    users = User.query.filter_by(admin=False).all()

    context = {
        'users' : users
    }

    return render_template('users.html', **context)

@main.route('/promote/<int:user_id>')
@login_required
def promote(user_id):
    if not current_user.admin:
        return redirect(url_for('main.index'))

    user = User.query.get_or_404(user_id)

    user.expert = True
    db.session.commit()

    return redirect(url_for('main.users'))

flask_qa/templates/answer.html
{% extends 'base.html' %}
{% block title %}Answer Question{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>{{ question.question }}</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('main.answer', question_id=question.id) }}">
                <fieldset>
                  <div class="form-group">
                    <label for="textArea" class="col-lg-2 control-label">Answer</label>
                    <div class="col-lg-10">
                      <textarea class="form-control" name="answer" rows="3" id="textArea"></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

flask_qa/templates/ask.html
{% extends 'base.html' %}
{% block title %}Ask a Question{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Ask A Question</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="well bs-component">
            <form class="form-horizontal" method="POST" action="{{ url_for('main.ask') }}">
              <fieldset>
                <div class="form-group">
                  <label for="textArea" class="col-lg-2 control-label">Question</label>
                    <div class="col-lg-10">
                      <textarea class="form-control" name="question" rows="3" id="textArea"></textarea>
                      <span class="help-block">Ask away!</span>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="select" class="col-lg-2 control-label">Expert</label>
                    <div class="col-lg-10">
                      <select class="form-control" name="expert" id="select">
                        {% for expert in experts %}
                        <option value="{{ expert.id }}">{{ expert.name }}</option>
                        {% endfor %}
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

flask_qa/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">
    
    <link href="{{ url_for('static', filename='theme.css') }}" rel="stylesheet">
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Questions & Answers</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.index') }}">Home</a></li>
            {% if not current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            <li><a href="{{ url_for('auth.register') }}">Register</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('main.ask') }}">Ask Question</a></li>
            {% endif %}
            {% if current_user.is_authenticated and current_user.expert %}
            <li><a href="{{ url_for('main.unanswered') }}">Unanswered Questions</a></li>
            {% endif %}
            {% if current_user.is_authenticated and current_user.admin %}
            <li><a href="{{ url_for('main.users') }}">User Setup</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      {% block content %}{% endblock %}

    </div> <!-- /container -->

  </body>
</html>

flask_qa/templates/home.html
{% extends 'base.html' %}
{% block title %}Questions & Answers{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Answered Questions</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group">
            {% for question in questions %}
              <a href="{{ url_for('main.question', question_id=question.id) }}" class="list-group-item">
                <h4 class="list-group-item-heading">{{ question.question }}</h4>
                <p class="list-group-item-text">Asked by: {{ question.asker.name }}</p>
                <p class="list-group-item-text">Answered by: {{ question.expert.name }}</p>
              </a>
            {% endfor %}
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}

flask_qa/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Login</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('auth.login') }}">
                <fieldset>
                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Name</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name" id="inputName" placeholder="Name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Password</label>
                    <div class="col-lg-10">
                      <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

flask_qa/templates/question.html
{% extends 'base.html' %}
{% block title %}Question{% endblock %}

{% block content %}
<div class="jumbotron">
        <h1>{{ question.question }}</h1>
        <p>{{ question.answer }}</p>
        <p><a class="btn btn-primary btn-lg">Asked By: {{ question.asker.name }}</a></p>
        <p><a class="btn btn-primary btn-lg">Answered By: {{ question.expert.name }}</a></p>
      </div>
{% endblock %}

flask_qa/templates/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Register</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('auth.register') }}">
                <fieldset>
                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Name</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name" id="inputName" placeholder="Name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Password</label>
                    <div class="col-lg-10">
                      <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
{% endblock %}

flask_qa/templates/unanswered.html
{% extends 'base.html' %}
{% block title %}Unaswered Questions{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Questions For You</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group">
            {% for question in unanswered_questions %}
              <a href="{{ url_for('main.answer', question_id=question.id) }}" class="list-group-item">
                <h4 class="list-group-item-heading">{{ question.question }}</h4>
                <p class="list-group-item-text">Asked by: {{ question.asker.name }}</p>
              </a>
            {% endfor %}
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}

flask_qa/templates/users.html
{% extends 'base.html' %}
{% block title %}Users{% endblock %}

{% block content %}
<div class="page-header">
        <h1>Users</h1>
        <h6>Click to promote to expert</h6>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group">
            {% for user in users %}
              <a href="{{ url_for('main.promote', user_id=user.id) }}" class="list-group-item {% if user.expert %}active{% endif %}">
                <h4 class="list-group-item-heading">{{ user.name }}</h4>
              </a>
            {% endfor %}
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}